export const LIFT_STATE = {
  OPENING: 'OPENING',
  CLOSING: 'CLOSING',
  MOVING_UP: 'MOVING_UP',
  MOVING_DOWN: 'MOVING_DOWN',
  LOCKED: 'LOCKED',
}

export const DIMENSIONS = {
  FLOOR_HEIGHT_PX: 100,
}