export const LIFT_STATE = {
  OPENING: 'OPENING',
  CLOSING: 'CLOSING',
  CLOSED: 'CLOSED',
  MOVING: 'MOVING',
  LOCKED: 'LOCKED',
}

export const LIFT_EVENT = {
  FLOOR_REACHED: 'FLOOR_REACHED',
  IS_IDLE: 'IS_IDLE',
  STARTED_MOVING: 'STARTED_MOVING',
  DOOR_OPEN: 'DOOR_OPEN',
}

export const FLOOR_EVENT = {
  FLOOR_BUTTON_UP_CLICK: 'FLOOR_BUTTON_UP_CLICK',
  FLOOR_BUTTON_DOWN_CLICK: 'FLOOR_BUTTON_DOWN_CLICK',
}

export const LIFT_STATS = {
  MAX_VELOCITY: 1000,
  ACCELERATION: 300,
  TIME_TO_OPEN_DOOR_IN_MILLI_SECONDS: 1000,
}

export const DIMENSIONS = {
  FLOOR_HEIGHT_PX: 150,
  LIFT_GAP: 60,
  FIRST_LIFT_GAP: 100,
}