export const LIFT_STATE = {
  OPENING: 'OPENING',
  CLOSING: 'CLOSING',
  CLOSED: 'CLOSED',
  MOVING: 'MOVING',
  LOCKED: 'LOCKED',
}

export const DIMENSIONS = {
  FLOOR_HEIGHT_PX: 100,
  LIFT_TIME_TO_COVER_FLOOR_IN_MILLI_SECONDS: 2000,
  LIFT_GAP: 60,
}